services:
  tg-downloader:
    build: .
    container_name: tg-downloader
    restart: always
    volumes:
      - ./config.yaml:/app/config.yaml:ro
      - ./data:/app/data
      - /srv/share/tg-downloads:/srv/share/tg-downloads
    stdin_open: true
    tty: true
